### ISSUE TITLE
future compatibility problem in dependencies

### ISSUE THREAD

**Issue by hdhoang** [bddap/watch-stl-rust#2]
Hi, due to rust-lang/rust#49799, one of your dependencies will no longer build. From looking at your
Cargo.toml, we recommend you upgrade to
nalgebra version 0.14.4 or later (and kiss3d too I think). Thanks for your attention!

**Comment by bddap** [comment]
Thanks! Should be fixed by d9238a6ba446bdb2c1ecc132131cbed6fb27ce3c which removes the explicit nalgebra as a dependency in favor of the version bundled with kiss3d. It also updates kiss3d.
