### ISSUE TITLE
Buggy reloading behavior

### ISSUE THREAD

**Issue by maybeetree** [bddap/watch-stl-rust#5]
Expected behavior: When the STL file updates to contain the a new model, WatchSTL displays that new model.

Actual behavior: When the STL file updates, one of three things can happen:

1. The model updates as expected
2. The model does not update, and watchstl continues displaying the model as defined by the old file.
3. The model *does* update, but the previous version is not removed properly, leaving both the old and the new version visible at the same time. 
4. Rarely, the following error occurs and watch-stl crashes: `Error: failed to fill whole buffer`

This behavior feels very random/inconsistent, perhaps its a race condition? Moreover, it happens regardless of whether the file is updated by moving a new one in its place (e.g. `cp some_other_model.stl watched_model.stl`) or writing to it directly (e.g. `cat some_other_model.stl > watched_model.stl`). Finally, as expected, re-starting watch-stl always loads the new model properly.

Thanks in advance for your help, and please let me know if you can't reproduce the bug / need more information.

**Comment by bddap** [comment]
Guessing most of this is because the program is trying to load the stl before it is done being written. A possible fix is to handle failure to load the file displaying an "X" or something when the file fails to load then waiting for the next update.

**Comment by bddap** [comment]
3. was caused by a logic error where only the first update did replace the mesh
4. was caused by the program terminating when it encountered an invalid mesh

I never did repo 2. but I'll assume for now that it was fixed by https://github.com/bddap/watch-stl-rust/commit/4148697ac5f77016ff5b834a849daf9c0a33961f . Do feel free to repopen this issue if 2. is still a problem.

**Comment by bddap** [comment]
Guessing 2. was a special case of 3. where the new mesh was inside the old one so it was hidden.
